PREFIX ce: <http://cineexplorer.local/ontology#>

ASK {
  BIND(<http://cineexplorer.local/data/person/nm0000102> AS ?source)
  BIND(<http://cineexplorer.local/data/person/nm0000158> AS ?target)
  ?source (ce:workedFor/ce:employed){1,1} ?target .
  FILTER(?source != ?target)
}
