connectionURL = jdbc:mysql://127.0.0.1:3307/imdb
user = imdb_user
password = imdb_pass

mappingFile = cineexplorer_mapping.ttl
outputFile = ../output/cineexplorer_kg_v2.ttl
format = TURTLE


# connectionURL = jdbc:mysql://localhost:3307/imdb
# user = imdb_user
# password = imdb_pass
# mappingFile = /mnt/data/cineexplorer_mapping.ttl
# outputFile = /mnt/data/cineexplorer_kg_v2.ttl
# format = TURTLE
